version: "3"

networks:
  frontend:
    external: true
  forem_backend:
    internal: true

services:
  rails:
    image: quay.io/forem/forem:development
    container_name: forem_rails
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - bundle
      - db
      - redis
      - yarn
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_development
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
      APP_DOMAIN: rails
    volumes:
      - .:/opt/apps/forem:delegated
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "file:///opt/apps/forem/vendor/bundle/.bundle_finished", "-timeout", "2700s", "-wait-retry-interval", "10s"]
    command: [ "bash", "-c", "./scripts/entrypoint.sh bootstrap && bundle exec rails server -b 0.0.0.0 -p 3000"]
    networks:
      - forem_backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forem.entrypoints=web,websecure"
      - "traefik.http.routers.forem.rule=Host(`forem.cloud.themaymeow.com`)"
      - "traefik.http.routers.forem.tls=true"
      - "traefik.http.routers.forem.tls.certresolver=le"
      - "traefik.http.routers.forem.tls.options=mytls@file"
      - "traefik.http.routers.forem.service=forem"
      - "traefik.http.services.forem.loadbalancer.server.port=3000"
      - "traefik.docker.network=frontend"

  bundle:
    image: quay.io/forem/forem:development
    container_name: forem_bundle
    user: root
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_development
    volumes:
      - .:/opt/apps/forem:delegated
    command: ["./scripts/bundle.sh"]
    networks: 
      - forem_backend

  yarn:
    image: quay.io/forem/forem:development
    container_name: forem_yarn
    user: root
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_development
    volumes:
      - .:/opt/apps/forem:delegated
    command: yarn install --dev
    networks: 
      - forem_backend

  webpacker:
    image: quay.io/forem/forem:development
    container_name: forem_webpacker
    user: root
    depends_on:
      - bundle
      - rails
      - yarn
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_development
    volumes:
      - .:/opt/apps/forem:delegated
    entrypoint: ["dockerize", "-wait", "file:///opt/apps/forem/node_modules/.bin/webpack-dev-server", "-wait", "file:///opt/apps/forem/vendor/bundle/.bundle_finished", "-timeout", "2700s", "-wait-retry-interval", "10s"]
    command: ["./bin/webpack-dev-server"]
    networks: 
      - forem_backend

  seed:
    image: quay.io/forem/forem:development
    container_name: forem_seed
    user: root
    depends_on:
      - rails
      - redis
      - db
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_development
    volumes:
      - .:/opt/apps/forem:delegated
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "tcp://rails:3000", "-timeout", "2700s", "-wait-retry-interval", "20s"]
    command: ["bundle", "exec", "rake","db:seed"]
    networks: 
      - forem_backend

  sidekiq:
    image: quay.io/forem/forem:development
    container_name: forem_sidekiq
    user: root
    depends_on:
      - rails
      - redis
      - db
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_development
    volumes:
      - .:/opt/apps/forem:delegated
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "tcp://rails:3000", "-timeout", "2700s", "-wait-retry-interval", "20s"]
    command: ["bundle", "exec", "sidekiq","-c","2"]
    networks: 
      - forem_backend
      - frontend

  db:
    image: postgres:11-alpine
    container_name: forem_postgresql
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: PracticalDeveloper_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    networks: 
      - forem_backend

  redis:
    image: redis:6.0.9-alpine
    container_name: forem_redis
    ports:
      - "6379:6379"
    networks: 
      - forem_backend

volumes:
  db_data:
  letsencrypt-data:
